// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2022.2_1/1019737 Production Release
//       HLS date: Mon Nov 21 20:05:27 PST 2022
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: HLS_student@localhost.localdomain
// Generated date: Tue Feb 11 14:51:05 CET 2025
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model top_level
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Process: SC_METHOD update_proc
// Static sensitivity: sensitive  << clk << rst << data_in << valid_in << coeffs[0] << coeffs[1] << coeffs[2] << coeffs[3] << coeffs[4] << coeffs[5] << coeffs[6] << coeffs[7] << coeffs[8] << coeffs[9] << coeffs[10] << coeffs[11] << coeffs[12] << coeffs[13] << coeffs[14] << coeffs[15] << ccs_rtl_SIG_data_out << ccs_rtl_SIG_valid_out;

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   // none.sc_in field_key=clk:b65df48e-aadc-46be-ba0c-2f3837715dc5-568:clk:b65df48e-aadc-46be-ba0c-2f3837715dc5-568
   sc_logic t_b65df48e_aadc_46be_ba0c_2f3837715dc5_568_0; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:b65df48e-aadc-46be-ba0c-2f3837715dc5-569:rst:b65df48e-aadc-46be-ba0c-2f3837715dc5-569
   sc_logic t_b65df48e_aadc_46be_ba0c_2f3837715dc5_569_1; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_569_1); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_569_1); // then write to RTL port
   
   // none.sc_in field_key=data_in:b65df48e-aadc-46be-ba0c-2f3837715dc5-570:data_in:b65df48e-aadc-46be-ba0c-2f3837715dc5-570
   sc_lv< 24 > t_b65df48e_aadc_46be_ba0c_2f3837715dc5_570_2; // NPS - LV to hold field
   type_to_vector(data_in.read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_570_2); // read orig port and type convert
   ccs_rtl_SIG_data_in.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_570_2); // then write to RTL port
   
   // none.sc_in field_key=valid_in:b65df48e-aadc-46be-ba0c-2f3837715dc5-571:valid_in:b65df48e-aadc-46be-ba0c-2f3837715dc5-571
   sc_logic t_b65df48e_aadc_46be_ba0c_2f3837715dc5_571_3; // NPS - LV to hold field
   type_to_vector(valid_in.read(),1,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_571_3); // read orig port and type convert
   ccs_rtl_SIG_valid_in.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_571_3); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   sc_lv< 24 > t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4; // NPS - LV to hold field
   type_to_vector(coeffs[0].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_0.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[1].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_1.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[2].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_2.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[3].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_3.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[4].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_4.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[5].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_5.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[6].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_6.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[7].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_7.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[8].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_8.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[9].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_9.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[10].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_10.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[11].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_11.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[12].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_12.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[13].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_13.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[14].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_14.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_in field_key=coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572:coeffs:b65df48e-aadc-46be-ba0c-2f3837715dc5-572
   type_to_vector(coeffs[15].read(),24,t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // read orig port and type convert
   ccs_rtl_SIG_coeffs_15.write(t_b65df48e_aadc_46be_ba0c_2f3837715dc5_572_4); // then write to RTL port
   
   // none.sc_out field_key=data_out:b65df48e-aadc-46be-ba0c-2f3837715dc5-573:data_out:b65df48e-aadc-46be-ba0c-2f3837715dc5-573
   ac_fixed<24, 24, true, AC_RND_INF, AC_SAT > d_b65df48e_aadc_46be_ba0c_2f3837715dc5_573_20;
   vector_to_type(ccs_rtl_SIG_data_out.read(), 24, &d_b65df48e_aadc_46be_ba0c_2f3837715dc5_573_20);
   data_out.write(d_b65df48e_aadc_46be_ba0c_2f3837715dc5_573_20);
   
   // none.sc_out field_key=valid_out:b65df48e-aadc-46be-ba0c-2f3837715dc5-574:valid_out:b65df48e-aadc-46be-ba0c-2f3837715dc5-574
   bool d_b65df48e_aadc_46be_ba0c_2f3837715dc5_574_21;
   vector_to_type(ccs_rtl_SIG_valid_out.read(), 1, &d_b65df48e_aadc_46be_ba0c_2f3837715dc5_574_21);
   valid_out.write(d_b65df48e_aadc_46be_ba0c_2f3837715dc5_574_21);
   
}
