directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.imag(6).sva REGISTER_NAME output_fft.imag(6).sva
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.imag(6).sva.dfm.1 REGISTER_NAME output_fft.imag(6).sva
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.imag(2).sva REGISTER_NAME output_fft.imag(2).sva
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.imag(2).sva.dfm.1 REGISTER_NAME output_fft.imag(2).sva
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/BUT_S2-4:FFT::but#1:FFT::but#1:nor#13.itm.1 REGISTER_NAME BUT_S2-4:FFT::but#1:FFT::but#1:nor#13.itm.1
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.real(0).sva REGISTER_NAME BUT_S2-4:FFT::but#1:FFT::but#1:nor#13.itm.1
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/BUT_S2-4:FFT::but#1:conc.ncse(24:1).sva.1 REGISTER_NAME BUT_S2-4:FFT::but#1:conc.ncse(24:1).sva.1
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.real(2).sva REGISTER_NAME BUT_S2-4:FFT::but#1:conc.ncse(24:1).sva.1
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/BUT_S2-2:FFT::but#1:conc#7.ncse(24:1).sva.1 REGISTER_NAME BUT_S2-2:FFT::but#1:conc#7.ncse(24:1).sva.1
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.imag(0).sva REGISTER_NAME BUT_S2-2:FFT::but#1:conc#7.ncse(24:1).sva.1
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/BUT_S2-2:FFT::but#1:conc.ncse(24:1).sva.1 REGISTER_NAME BUT_S2-2:FFT::but#1:conc.ncse(24:1).sva.1
directive set /FFT/FFT:COMPORTEMENT/COMPORTEMENT/output_fft.imag(4).sva REGISTER_NAME BUT_S2-2:FFT::but#1:conc.ncse(24:1).sva.1
