// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2022.2_1/1019737 Production Release
//       HLS date: Mon Nov 21 20:05:27 PST 2022
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: HLS_student@localhost.localdomain
// Generated date: Tue Mar 18 15:47:28 CET 2025
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model FFT
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Process: SC_METHOD update_proc
// Static sensitivity: sensitive  << clk << rst << in_real << in_imag << ccs_rtl_SIG_out_real << ccs_rtl_SIG_out_imag << data_valid_source << ccs_rtl_SIG_data_req_source << ccs_rtl_SIG_data_valid_sink << data_req_sink;

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   // none.sc_in field_key=clk:734750f7-3680-4ef4-8ce7-2166d3edb043-489:clk:734750f7-3680-4ef4-8ce7-2166d3edb043-489
   sc_logic t_734750f7_3680_4ef4_8ce7_2166d3edb043_489_0; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:734750f7-3680-4ef4-8ce7-2166d3edb043-490:rst:734750f7-3680-4ef4-8ce7-2166d3edb043-490
   sc_logic t_734750f7_3680_4ef4_8ce7_2166d3edb043_490_1; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_734750f7_3680_4ef4_8ce7_2166d3edb043_490_1); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_734750f7_3680_4ef4_8ce7_2166d3edb043_490_1); // then write to RTL port
   
   // none.sc_in field_key=in_real:734750f7-3680-4ef4-8ce7-2166d3edb043-491:in_real:734750f7-3680-4ef4-8ce7-2166d3edb043-491
   sc_lv< 23 > t_734750f7_3680_4ef4_8ce7_2166d3edb043_491_2; // NPS - LV to hold field
   type_to_vector(in_real.read(),23,t_734750f7_3680_4ef4_8ce7_2166d3edb043_491_2); // read orig port and type convert
   ccs_rtl_SIG_in_real.write(t_734750f7_3680_4ef4_8ce7_2166d3edb043_491_2); // then write to RTL port
   
   // none.sc_in field_key=in_imag:734750f7-3680-4ef4-8ce7-2166d3edb043-492:in_imag:734750f7-3680-4ef4-8ce7-2166d3edb043-492
   sc_lv< 23 > t_734750f7_3680_4ef4_8ce7_2166d3edb043_492_3; // NPS - LV to hold field
   type_to_vector(in_imag.read(),23,t_734750f7_3680_4ef4_8ce7_2166d3edb043_492_3); // read orig port and type convert
   ccs_rtl_SIG_in_imag.write(t_734750f7_3680_4ef4_8ce7_2166d3edb043_492_3); // then write to RTL port
   
   // none.sc_out field_key=out_real:734750f7-3680-4ef4-8ce7-2166d3edb043-493:out_real:734750f7-3680-4ef4-8ce7-2166d3edb043-493
   ac_fixed<23, 18, true, AC_TRN, AC_WRAP > d_734750f7_3680_4ef4_8ce7_2166d3edb043_493_4;
   vector_to_type(ccs_rtl_SIG_out_real.read(), 23, &d_734750f7_3680_4ef4_8ce7_2166d3edb043_493_4);
   out_real.write(d_734750f7_3680_4ef4_8ce7_2166d3edb043_493_4);
   
   // none.sc_out field_key=out_imag:734750f7-3680-4ef4-8ce7-2166d3edb043-494:out_imag:734750f7-3680-4ef4-8ce7-2166d3edb043-494
   ac_fixed<23, 18, true, AC_TRN, AC_WRAP > d_734750f7_3680_4ef4_8ce7_2166d3edb043_494_5;
   vector_to_type(ccs_rtl_SIG_out_imag.read(), 23, &d_734750f7_3680_4ef4_8ce7_2166d3edb043_494_5);
   out_imag.write(d_734750f7_3680_4ef4_8ce7_2166d3edb043_494_5);
   
   // none.sc_in field_key=data_valid_source:734750f7-3680-4ef4-8ce7-2166d3edb043-495:data_valid_source:734750f7-3680-4ef4-8ce7-2166d3edb043-495
   sc_logic t_734750f7_3680_4ef4_8ce7_2166d3edb043_495_6; // NPS - LV to hold field
   type_to_vector(data_valid_source.read(),1,t_734750f7_3680_4ef4_8ce7_2166d3edb043_495_6); // read orig port and type convert
   ccs_rtl_SIG_data_valid_source.write(t_734750f7_3680_4ef4_8ce7_2166d3edb043_495_6); // then write to RTL port
   
   // none.sc_out field_key=data_req_source:734750f7-3680-4ef4-8ce7-2166d3edb043-496:data_req_source:734750f7-3680-4ef4-8ce7-2166d3edb043-496
   bool d_734750f7_3680_4ef4_8ce7_2166d3edb043_496_7;
   vector_to_type(ccs_rtl_SIG_data_req_source.read(), 1, &d_734750f7_3680_4ef4_8ce7_2166d3edb043_496_7);
   data_req_source.write(d_734750f7_3680_4ef4_8ce7_2166d3edb043_496_7);
   
   // none.sc_out field_key=data_valid_sink:734750f7-3680-4ef4-8ce7-2166d3edb043-497:data_valid_sink:734750f7-3680-4ef4-8ce7-2166d3edb043-497
   bool d_734750f7_3680_4ef4_8ce7_2166d3edb043_497_8;
   vector_to_type(ccs_rtl_SIG_data_valid_sink.read(), 1, &d_734750f7_3680_4ef4_8ce7_2166d3edb043_497_8);
   data_valid_sink.write(d_734750f7_3680_4ef4_8ce7_2166d3edb043_497_8);
   
   // none.sc_in field_key=data_req_sink:734750f7-3680-4ef4-8ce7-2166d3edb043-498:data_req_sink:734750f7-3680-4ef4-8ce7-2166d3edb043-498
   sc_logic t_734750f7_3680_4ef4_8ce7_2166d3edb043_498_9; // NPS - LV to hold field
   type_to_vector(data_req_sink.read(),1,t_734750f7_3680_4ef4_8ce7_2166d3edb043_498_9); // read orig port and type convert
   ccs_rtl_SIG_data_req_sink.write(t_734750f7_3680_4ef4_8ce7_2166d3edb043_498_9); // then write to RTL port
   
}
